module Konjac
  # A class for managing the tags generated by extraction from {Microsoft
  # Word}[http://office.microsoft.com/en-us/word/] 2003+ documents
  class TagManager
    # A list of the Tag objects current being managed
    attr_accessor :tags

    # A regex to match lines that start with <tt>-</tt>, that is, lines that
    # indicate original text in .konjac files
    OLD_TAG = /^-[^-]/

    NEW_TAG = /^\+[^+]/

    # Regex for matching index numbers
    KONJAC_TAG = /^@@\s(\d+).*@@$/

    # Creates a new TagManager
    def initialize(path)
      @tags = []
      parse_lines File.readlines(path)
    end

    # Parses the lines of a file into Tag objects
    def parse_lines(lines)
      index      = nil
      orig       = nil
      trans      = nil

      lines.each do |line|
        if line =~ KONJAC_TAG
          # Handle instances where there is no translation
          unless orig.nil?
            @tags << Tag.new(index, orig, trans)
            index = nil
            orig  = nil
          end

          index = line.match(KONJAC_TAG)[1].to_i
        elsif line =~ OLD_TAG
          orig = line[1..-1].chomp
        elsif line =~ NEW_TAG
          trans = line[1..-1].chomp
          unless index.nil?
            @tags << Tag.new(index, orig, trans)
            index = nil
            orig  = nil
            trans = nil
          end
        end
      end
    end

    # A list of all the tags available
    def all
      @tags
    end

    # Finds the <em>nth</em> tag being managed
    def [](index)
      @tags[index]
    end
  end
end
